### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [aitecraft/shareenderchest#1]
Hello, I loved to saw your mod some days ago 😊

My question - do you think it would be possible to not override the normal ender chest?
Maybe renaming the item / or adding special NBT tags to access this new inventory this way?

Thanks already - greetings.

**Comment by kripesh101** [comment]
Thanks for using the mod!

Unfortunately, it seems named Ender Chest items don't retain their name when placed and mined (unlike chests or shulker boxes).
This means this option would work only in the inventory, and players must avoid placing the renamed Ender Chest or they'll have to rename the item once again. Is this compromised solution good enough? If it is, then I could look into it.

Alternatively, it could be possible to change the Ender Chest's block entity and loot table to retain names but I think that would be complicated and difficult to maintain as part of a simple mod like this.

It would also be difficult to distinguish a shared ender chest from a normal one. As an item, checking the name would suffice but when placed in the world, it would be impossible to know which is which unless you open it.

**Perhaps a better option:** If you haven't seen it yet, there's a mod that adds an entirely new block with similar functionality as this mod (with more features too!), but comes with the downside of requiring installation on both server and client. It's called [Nether Chest](https://modrinth.com/mod/nether-chest).
