### ISSUE TITLE
Update to 1.20.1 Please

### ISSUE THREAD

**Issue by sternschnaube** [aitecraft/shareenderchest#3]

**Comment by kripesh101** [comment]
After a bit of testing, it seems the 1.19.2 version of the mod works fine in 1.20.1.
I've also updated the modrinth page to show 1.20.1 compatibility.

If you find any crashes, please let me know!

**Comment by venaminecraft** [comment]
Great to hear that it works, I was testing it right now.
Everything is fine - thanks 😊
